# Generated by Django 2.2.6 on 2019-10-15 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuito_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.IntegerField()),
                ('escala', models.IntegerField()),
                ('datatype', models.CharField(choices=[('8', '8 bits'), ('16', '16 bits'), ('32', '32 bits')], default='16', max_length=2)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuito_config.Modulo')),
            ],
        ),
        migrations.CreateModel(
            name='Datalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuito_config.Parametro')),
            ],
        ),
    ]
