# Generated by Django 2.2.6 on 2019-10-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuito_config', '0002_datalog_parametro'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
