# Generated by Django 2.2.6 on 2019-11-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuito_config', '0005_parametro_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='baudrate',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='bytesize',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='parity',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='porta',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='stopbits',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='timeout',
        ),
        migrations.AddField(
            model_name='circuito',
            name='baudrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circuito',
            name='bytesize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circuito',
            name='parity',
            field=models.CharField(choices=[('N', 'None'), ('E', 'Even'), ('O', 'Odd'), ('M', 'Mark'), ('S', 'Space')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='circuito',
            name='porta',
            field=models.CharField(default='N', max_length=255),
        ),
        migrations.AddField(
            model_name='circuito',
            name='stopbits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circuito',
            name='timeout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circuito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circuito_config.Cliente'),
        ),
    ]
