# Generated by Django 2.2.6 on 2019-11-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuito_config', '0006_auto_20191104_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
