# Generated by Django 2.2.6 on 2019-11-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuito_config', '0007_parametro_signed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logerros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('datahora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
