# Generated by Django 2.2.6 on 2019-11-14 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuito_config', '0008_logerros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superaquecimentoconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('succao_no_slave', models.IntegerField()),
                ('succao_no_parametro', models.IntegerField()),
                ('evaporacao_no_slave', models.IntegerField()),
                ('evaporacao_no_parametro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Superaquecimentolog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.FloatField()),
                ('superaquecimento', models.BooleanField(default=True)),
                ('superaquecimentoconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuito_config.Superaquecimentoconfig')),
            ],
        ),
    ]
