# Generated by Django 2.2.6 on 2019-11-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuito_config', '0009_superaquecimentoconfig_superaquecimentolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='superaquecimentoconfig',
            name='max_superaquecimento',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='superaquecimentoconfig',
            name='min_superaquecimento',
            field=models.FloatField(default=0),
        ),
    ]
