# Generated by Django 2.2.6 on 2019-11-14 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('circuito_config', '0010_auto_20191114_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='superaquecimentolog',
            name='datahora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
