# Generated by Django 2.2.6 on 2019-12-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuito_config', '0012_alarme_alarmelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmelog',
            name='status',
        ),
        migrations.AddField(
            model_name='alarmelog',
            name='datalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuito_config.Datalog'),
        ),
    ]
