# Generated by Django 2.2.6 on 2019-12-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuito_config', '0014_auto_20191216_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarme',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
