# Generated by Django 2.2.6 on 2019-12-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuito_config', '0015_alarme_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatosalarme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('recebe_email', models.BooleanField(default=True)),
                ('recebe_sms', models.BooleanField(default=True)),
            ],
        ),
    ]
